//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelSoure.DataSoure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTest
    {
        public string id { get; set; }
        public string ticketName { get; set; }
        public Nullable<decimal> price { get; set; }
        public string remark { get; set; }
        public string seatNub { get; set; }
        public Nullable<int> totalNub { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public byte[] versionNum { get; set; }
    }
}
